export enum EnumTools {
    JSON_COMPRESS = "json-compress",
    JSON_FORMAT = "json-format",
    JSON_PARSE_DEEP = "json-parse-deep",
    JSON_SORT = "json-sort",
    JSON_TO_TS = "json-to-ts",
    JSON_TO_YAML = "json-to-yaml",
    YAML_TO_JSON = "yaml-to-json",
    JSON_FLAT = "json-flat",
    JSON_NESTING = "json-nesting",
    JSON_TO_CSV = "json-to-csv",
    TEXT_SIZE = "text-size",
    TEXT_DIFF = "text-diff",
    URL_PARSE = "url-parse",
}