export enum EnumTools {
    JSON_COMPRESS = "json-compress",
    JSON_FORMAT = "json-format",
    JSON_PARSE_DEEP = "json-parse-deep",
    JSON_SORT = "json-sort",
    JSON_TO_TS = "json-to-ts",
    JSON_TO_YAML = "json-to-yaml",
    YAML_TO_JSON = "yaml-to-json",
    JSON_FLAT = "json-flat",
    JSON_NESTING = "json-nesting",
    JSON_TO_CSV = "json-to-csv",
    CSV_TO_JSON = "csv-to-json",
    TEXT_SIZE = "text-size",
    TEXT_DIFF = "text-diff",
    URL_PARSE = "url-parse",
    URL_ENCODE = "url-encode",
    URL_DECODE = "url-decode",
    CSP_PARSE = "csp-parse",
    CSP_UNPARSE = "csp-unparse",
    OBJ_TO_JSON = "obj-to-json",
    JSON_TO_OBJ = "json-to-obj",
    BASE64_ENCODE = "base64-encode",
    BASE64_DECODE = "base64-decode",
    SQL_FORMAT = "sql-format",
    SQL_COMPRESS = "sql-compress",
}